## Specify the DBMS to use
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventorymanagement?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Dilane237
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

  jpa:
    database: mysql
    show-sql: false
    properties:
      hibernate:
        ejb:
          interceptor: com.kamtech.inventorymanagement.interceptor

## Hibernate DDL auto (create, create-drop, validate, update)
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

## Specify the port to use
server:
  port: 8081

# Configure flick API
flickr:
  apiKey: 0a2e56fd923296d7be07a4ca1266eb34
  apiSecret: ab1da2be832391e4
  appKey: 72157720882332575-4c5282da566d1b81
  appSecret: 548edf915a59bb9c






